insert into public.model_pricing_rules (
  provider,
  model,
  operation,
  display_name,
  markup_bps,
  minimum_charge_usd_micros,
  reserve_amount_usd_micros,
  enabled,
  metadata
)
values
  (
    'fal',
    'openai/gpt-image-2',
    'image_generation',
    'GPT Image 2',
    2000,
    100000,
    1000000,
    true,
    $${"public_id": "openai/gpt-image-2", "provider_endpoint": "openai/gpt-image-2", "kind": "image", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["image"], "pricing_unit": "job", "default_parameters": {"image_size": "landscape_4_3", "quality": "high", "num_images": 1, "output_format": "png", "sync_mode": false}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "image_size": {"oneOf": [{"type": "string", "enum": ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9", "auto"]}, {"type": "object", "required": ["width", "height"], "additionalProperties": false, "properties": {"width": {"type": "integer", "minimum": 16, "maximum": 3840}, "height": {"type": "integer", "minimum": 16, "maximum": 3840}}}], "default": "landscape_4_3"}, "quality": {"type": "string", "enum": ["auto", "low", "medium", "high"], "default": "high"}, "num_images": {"type": "integer", "minimum": 1, "maximum": 4, "default": 1}, "output_format": {"type": "string", "enum": ["jpeg", "png", "webp"], "default": "png"}, "sync_mode": {"type": "boolean", "default": false}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "gpt_image_conservative", "image_parameter": "num_images", "quality_parameter": "quality", "provider_rate_usd_by_quality": {"low": "0.20", "medium": "0.50", "high": "1.00", "auto": "1.00"}}, "fal_output_paths": [{"path": "images", "type": "image"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'openai/gpt-image-2/edit',
    'image_generation',
    'GPT Image 2 Edit',
    2000,
    100000,
    1000000,
    true,
    $${"public_id": "openai/gpt-image-2/edit", "provider_endpoint": "openai/gpt-image-2/edit", "kind": "image", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["image"], "pricing_unit": "job", "default_parameters": {"image_size": "landscape_4_3", "quality": "high", "num_images": 1, "output_format": "png", "sync_mode": false}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "image_size": {"oneOf": [{"type": "string", "enum": ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9", "auto"]}, {"type": "object", "required": ["width", "height"], "additionalProperties": false, "properties": {"width": {"type": "integer", "minimum": 16, "maximum": 3840}, "height": {"type": "integer", "minimum": 16, "maximum": 3840}}}], "default": "landscape_4_3"}, "quality": {"type": "string", "enum": ["auto", "low", "medium", "high"], "default": "high"}, "num_images": {"type": "integer", "minimum": 1, "maximum": 4, "default": 1}, "output_format": {"type": "string", "enum": ["jpeg", "png", "webp"], "default": "png"}, "sync_mode": {"type": "boolean", "default": false}}}, "input_asset_schema": {"roles": [{"role": "reference_images", "provider_field": "image_urls", "media_kind": "image", "required": true, "min": 1, "max": 4, "content_type_prefixes": ["image/"]}, {"role": "mask", "provider_field": "mask_url", "media_kind": "image", "required": false, "min": 0, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "gpt_image_conservative", "image_parameter": "num_images", "quality_parameter": "quality", "provider_rate_usd_by_quality": {"low": "0.20", "medium": "0.50", "high": "1.00", "auto": "1.00"}}, "fal_output_paths": [{"path": "images", "type": "image"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/nano-banana-pro',
    'image_generation',
    'Nano Banana Pro',
    2000,
    100000,
    360000,
    true,
    $${"public_id": "fal-ai/nano-banana-pro", "provider_endpoint": "fal-ai/nano-banana-pro", "kind": "image", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["image"], "pricing_unit": "job", "default_parameters": {"num_images": 1, "aspect_ratio": "1:1", "output_format": "png", "safety_tolerance": "4", "sync_mode": false, "system_prompt": "", "resolution": "1K", "limit_generations": false, "enable_web_search": false}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "num_images": {"type": "integer", "minimum": 1, "maximum": 4, "default": 1}, "seed": {"type": "integer"}, "aspect_ratio": {"type": "string", "enum": ["auto", "21:9", "16:9", "3:2", "4:3", "5:4", "1:1", "4:5", "3:4", "2:3", "9:16"], "default": "1:1"}, "output_format": {"type": "string", "enum": ["jpeg", "png", "webp"], "default": "png"}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}, "sync_mode": {"type": "boolean", "default": false}, "system_prompt": {"type": "string", "default": ""}, "resolution": {"type": "string", "enum": ["1K", "2K", "4K"], "default": "1K"}, "limit_generations": {"type": "boolean", "default": false}, "enable_web_search": {"type": "boolean", "default": false}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "nano_banana", "image_parameter": "num_images", "resolution_parameter": "resolution", "web_search_parameter": "enable_web_search", "provider_rate_usd_per_image": "0.15", "provider_rate_usd_per_web_search": "0.015", "four_k_multiplier": 2}, "fal_output_paths": [{"path": "images", "type": "image"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'google/nano-banana-2-lite',
    'image_generation',
    'Nano Banana 2 Lite',
    2000,
    0,
    47760,
    true,
    $${"public_id": "google/nano-banana-2-lite", "provider_endpoint": "google/nano-banana-2-lite", "kind": "image", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["image"], "pricing_unit": "job", "default_parameters": {"num_images": 1, "aspect_ratio": "auto", "output_format": "png", "safety_tolerance": "4", "sync_mode": false, "system_prompt": "", "limit_generations": true}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 3, "maxLength": 50000}, "num_images": {"type": "integer", "minimum": 1, "maximum": 4, "default": 1}, "seed": {"type": "integer"}, "aspect_ratio": {"type": "string", "enum": ["auto", "21:9", "16:9", "3:2", "4:3", "5:4", "1:1", "4:5", "3:4", "2:3", "9:16", "4:1", "1:4", "8:1", "1:8"], "default": "auto"}, "output_format": {"type": "string", "enum": ["jpeg", "png", "webp"], "default": "png"}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}, "sync_mode": {"type": "boolean", "default": false}, "system_prompt": {"type": "string", "maxLength": 50000, "default": ""}, "limit_generations": {"type": "boolean", "default": true}, "thinking_level": {"type": "string", "enum": ["minimal", "high"]}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "nano_banana", "image_parameter": "num_images", "provider_rate_usd_per_image": "0.0398"}, "fal_output_paths": [{"path": "images", "type": "image"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'google/nano-banana-2-lite/edit',
    'image_generation',
    'Nano Banana 2 Lite Edit',
    2000,
    0,
    47760,
    true,
    $${"public_id": "google/nano-banana-2-lite/edit", "provider_endpoint": "google/nano-banana-2-lite/edit", "kind": "image", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["image"], "pricing_unit": "job", "default_parameters": {"num_images": 1, "aspect_ratio": "auto", "output_format": "png", "safety_tolerance": "4", "sync_mode": false, "system_prompt": "", "limit_generations": true}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 3, "maxLength": 50000}, "num_images": {"type": "integer", "minimum": 1, "maximum": 4, "default": 1}, "seed": {"type": "integer"}, "aspect_ratio": {"type": "string", "enum": ["auto", "21:9", "16:9", "3:2", "4:3", "5:4", "3:4", "1:1", "2:3", "9:16", "4:1", "1:4", "8:1", "1:8"], "default": "auto"}, "output_format": {"type": "string", "enum": ["jpeg", "png", "webp"], "default": "png"}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}, "sync_mode": {"type": "boolean", "default": false}, "system_prompt": {"type": "string", "maxLength": 50000, "default": ""}, "limit_generations": {"type": "boolean", "default": true}, "thinking_level": {"type": "string", "enum": ["minimal", "high"]}}}, "input_asset_schema": {"roles": [{"role": "reference_images", "provider_field": "image_urls", "media_kind": "image", "required": true, "min": 1, "max": 4, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "nano_banana", "image_parameter": "num_images", "provider_rate_usd_per_image": "0.0398"}, "fal_output_paths": [{"path": "images", "type": "image"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/gemini-omni-flash',
    'video_generation',
    'Gemini Omni Flash',
    2000,
    100000,
    1200000,
    true,
    $${"public_id": "fal-ai/gemini-omni-flash", "provider_endpoint": "fal-ai/gemini-omni-flash", "kind": "video", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["video"], "pricing_unit": "job", "default_parameters": {"aspect_ratio": "16:9", "duration": 8}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16"], "default": "16:9"}, "duration": {"type": "integer", "minimum": 3, "maximum": 10, "default": 8}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "gemini_unit", "provider_rate_usd_per_generation": "1.00"}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/gemini-omni-flash/image-to-video',
    'video_generation',
    'Gemini Omni Flash Image to Video',
    2000,
    100000,
    1200000,
    true,
    $${"public_id": "fal-ai/gemini-omni-flash/image-to-video", "provider_endpoint": "fal-ai/gemini-omni-flash/image-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "job", "default_parameters": {"aspect_ratio": "16:9", "duration": 8}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16"], "default": "16:9"}, "duration": {"type": "integer", "minimum": 3, "maximum": 10, "default": 8}}}, "input_asset_schema": {"roles": [{"role": "image", "provider_field": "image_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "gemini_unit", "provider_rate_usd_per_generation": "1.00"}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/gemini-omni-flash/reference-to-video',
    'video_generation',
    'Gemini Omni Flash Reference to Video',
    2000,
    100000,
    1200000,
    true,
    $${"public_id": "fal-ai/gemini-omni-flash/reference-to-video", "provider_endpoint": "fal-ai/gemini-omni-flash/reference-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "job", "default_parameters": {"aspect_ratio": "16:9", "duration": 8}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16"], "default": "16:9"}, "duration": {"type": "integer", "minimum": 3, "maximum": 10, "default": 8}}}, "input_asset_schema": {"roles": [{"role": "reference_images", "provider_field": "image_urls", "media_kind": "image", "required": true, "min": 1, "max": 4, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "gemini_unit", "provider_rate_usd_per_generation": "1.00"}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/gemini-omni-flash/edit',
    'video_generation',
    'Gemini Omni Flash Edit',
    2000,
    100000,
    1200000,
    true,
    $${"public_id": "fal-ai/gemini-omni-flash/edit", "provider_endpoint": "fal-ai/gemini-omni-flash/edit", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["video"], "output_types": ["video"], "pricing_unit": "job", "default_parameters": {"aspect_ratio": "16:9", "duration": 8}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16"], "default": "16:9"}, "duration": {"type": "integer", "minimum": 3, "maximum": 10, "default": 8}}}, "input_asset_schema": {"roles": [{"role": "video", "provider_field": "video_url", "media_kind": "video", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["video/"]}]}, "pricing_formula": {"type": "gemini_unit", "provider_rate_usd_per_generation": "1.00"}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/veo3.1',
    'video_generation',
    'Veo 3.1',
    2000,
    100000,
    5760000,
    true,
    $${"public_id": "fal-ai/veo3.1", "provider_endpoint": "fal-ai/veo3.1", "kind": "video", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"aspect_ratio": "16:9", "duration": "8s", "resolution": "720p", "generate_audio": true, "auto_fix": true, "safety_tolerance": "4"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16"], "default": "16:9"}, "duration": {"type": "string", "enum": ["4s", "6s", "8s"], "default": "8s"}, "negative_prompt": {"type": "string"}, "resolution": {"type": "string", "enum": ["720p", "1080p", "4k"], "default": "720p"}, "generate_audio": {"type": "boolean", "default": true}, "seed": {"type": "integer"}, "auto_fix": {"type": "boolean", "default": true}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "veo_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.20", "audio": "0.40"}, "4k": {"no_audio": "0.40", "audio": "0.60"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/veo3.1/image-to-video',
    'video_generation',
    'Veo 3.1 Image to Video',
    2000,
    100000,
    5760000,
    true,
    $${"public_id": "fal-ai/veo3.1/image-to-video", "provider_endpoint": "fal-ai/veo3.1/image-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"aspect_ratio": "auto", "duration": "8s", "resolution": "720p", "generate_audio": true, "auto_fix": false, "safety_tolerance": "4"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["auto", "16:9", "9:16"], "default": "auto"}, "duration": {"type": "string", "enum": ["4s", "6s", "8s"], "default": "8s"}, "negative_prompt": {"type": "string"}, "resolution": {"type": "string", "enum": ["720p", "1080p", "4k"], "default": "720p"}, "generate_audio": {"type": "boolean", "default": true}, "seed": {"type": "integer"}, "auto_fix": {"type": "boolean", "default": false}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}}}, "input_asset_schema": {"roles": [{"role": "image", "provider_field": "image_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "veo_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.20", "audio": "0.40"}, "4k": {"no_audio": "0.40", "audio": "0.60"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/veo3.1/first-last-frame-to-video',
    'video_generation',
    'Veo 3.1 First Last Frame to Video',
    2000,
    100000,
    5760000,
    true,
    $${"public_id": "fal-ai/veo3.1/first-last-frame-to-video", "provider_endpoint": "fal-ai/veo3.1/first-last-frame-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"aspect_ratio": "auto", "duration": "8s", "resolution": "720p", "generate_audio": true, "auto_fix": false, "safety_tolerance": "4"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["auto", "16:9", "9:16"], "default": "auto"}, "duration": {"type": "string", "enum": ["4s", "6s", "8s"], "default": "8s"}, "negative_prompt": {"type": "string"}, "resolution": {"type": "string", "enum": ["720p", "1080p", "4k"], "default": "720p"}, "generate_audio": {"type": "boolean", "default": true}, "seed": {"type": "integer"}, "auto_fix": {"type": "boolean", "default": false}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}}}, "input_asset_schema": {"roles": [{"role": "first_frame", "provider_field": "first_frame_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}, {"role": "last_frame", "provider_field": "last_frame_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "veo_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.20", "audio": "0.40"}, "4k": {"no_audio": "0.40", "audio": "0.60"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/veo3.1/reference-to-video',
    'video_generation',
    'Veo 3.1 Reference to Video',
    2000,
    100000,
    5760000,
    true,
    $${"public_id": "fal-ai/veo3.1/reference-to-video", "provider_endpoint": "fal-ai/veo3.1/reference-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"aspect_ratio": "16:9", "duration": "8s", "resolution": "720p", "generate_audio": true, "auto_fix": false, "safety_tolerance": "4"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16"], "default": "16:9"}, "duration": {"type": "string", "enum": ["4s", "6s", "8s"], "default": "8s"}, "negative_prompt": {"type": "string"}, "resolution": {"type": "string", "enum": ["720p", "1080p", "4k"], "default": "720p"}, "generate_audio": {"type": "boolean", "default": true}, "seed": {"type": "integer"}, "auto_fix": {"type": "boolean", "default": false}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}}}, "input_asset_schema": {"roles": [{"role": "reference_images", "provider_field": "image_urls", "media_kind": "image", "required": true, "min": 1, "max": 4, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "veo_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.20", "audio": "0.40"}, "4k": {"no_audio": "0.40", "audio": "0.60"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/veo3.1/fast',
    'video_generation',
    'Veo 3.1 Fast',
    2000,
    100000,
    3360000,
    true,
    $${"public_id": "fal-ai/veo3.1/fast", "provider_endpoint": "fal-ai/veo3.1/fast", "kind": "video", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"aspect_ratio": "16:9", "duration": "8s", "resolution": "720p", "generate_audio": true, "auto_fix": true, "safety_tolerance": "4"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16"], "default": "16:9"}, "duration": {"type": "string", "enum": ["4s", "6s", "8s"], "default": "8s"}, "negative_prompt": {"type": "string"}, "resolution": {"type": "string", "enum": ["720p", "1080p", "4k"], "default": "720p"}, "generate_audio": {"type": "boolean", "default": true}, "seed": {"type": "integer"}, "auto_fix": {"type": "boolean", "default": true}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "veo_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.10", "audio": "0.15"}, "4k": {"no_audio": "0.30", "audio": "0.35"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/veo3.1/fast/image-to-video',
    'video_generation',
    'Veo 3.1 Fast Image to Video',
    2000,
    100000,
    3360000,
    true,
    $${"public_id": "fal-ai/veo3.1/fast/image-to-video", "provider_endpoint": "fal-ai/veo3.1/fast/image-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"aspect_ratio": "auto", "duration": "8s", "resolution": "720p", "generate_audio": true, "auto_fix": false, "safety_tolerance": "4"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["auto", "16:9", "9:16"], "default": "auto"}, "duration": {"type": "string", "enum": ["4s", "6s", "8s"], "default": "8s"}, "negative_prompt": {"type": "string"}, "resolution": {"type": "string", "enum": ["720p", "1080p", "4k"], "default": "720p"}, "generate_audio": {"type": "boolean", "default": true}, "seed": {"type": "integer"}, "auto_fix": {"type": "boolean", "default": false}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}}}, "input_asset_schema": {"roles": [{"role": "image", "provider_field": "image_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "veo_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.10", "audio": "0.15"}, "4k": {"no_audio": "0.30", "audio": "0.35"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/veo3.1/fast/first-last-frame-to-video',
    'video_generation',
    'Veo 3.1 Fast First Last Frame to Video',
    2000,
    100000,
    3360000,
    true,
    $${"public_id": "fal-ai/veo3.1/fast/first-last-frame-to-video", "provider_endpoint": "fal-ai/veo3.1/fast/first-last-frame-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"aspect_ratio": "auto", "duration": "8s", "resolution": "720p", "generate_audio": true, "auto_fix": false, "safety_tolerance": "4"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "aspect_ratio": {"type": "string", "enum": ["auto", "16:9", "9:16"], "default": "auto"}, "duration": {"type": "string", "enum": ["4s", "6s", "8s"], "default": "8s"}, "negative_prompt": {"type": "string"}, "resolution": {"type": "string", "enum": ["720p", "1080p", "4k"], "default": "720p"}, "generate_audio": {"type": "boolean", "default": true}, "seed": {"type": "integer"}, "auto_fix": {"type": "boolean", "default": false}, "safety_tolerance": {"type": "string", "enum": ["1", "2", "3", "4", "5", "6"], "default": "4"}}}, "input_asset_schema": {"roles": [{"role": "first_frame", "provider_field": "first_frame_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}, {"role": "last_frame", "provider_field": "last_frame_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "veo_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.10", "audio": "0.15"}, "4k": {"no_audio": "0.30", "audio": "0.35"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'bytedance/seedance-2.0/text-to-video',
    'video_generation',
    'Seedance 2.0 Text to Video',
    2000,
    100000,
    9820800,
    true,
    $${"public_id": "bytedance/seedance-2.0/text-to-video", "provider_endpoint": "bytedance/seedance-2.0/text-to-video", "kind": "video", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"resolution": "720p", "duration": "5", "aspect_ratio": "auto", "generate_audio": true, "bitrate_mode": "standard"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "resolution": {"type": "string", "enum": ["480p", "720p", "1080p", "4k"], "default": "720p"}, "duration": {"type": "string", "enum": ["4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "aspect_ratio": {"type": "string", "enum": ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], "default": "auto"}, "generate_audio": {"type": "boolean", "default": true}, "bitrate_mode": {"type": "string", "enum": ["standard", "high"], "default": "standard"}, "end_user_id": {"type": "string"}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "seedance_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"480p": "0.3034", "720p": "0.3034", "1080p": "0.682", "4k": "0.682"}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'bytedance/seedance-2.0/image-to-video',
    'video_generation',
    'Seedance 2.0 Image to Video',
    2000,
    100000,
    9820800,
    true,
    $${"public_id": "bytedance/seedance-2.0/image-to-video", "provider_endpoint": "bytedance/seedance-2.0/image-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"resolution": "720p", "duration": "5", "aspect_ratio": "auto", "generate_audio": true, "bitrate_mode": "standard"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "resolution": {"type": "string", "enum": ["480p", "720p", "1080p", "4k"], "default": "720p"}, "duration": {"type": "string", "enum": ["4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "aspect_ratio": {"type": "string", "enum": ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], "default": "auto"}, "generate_audio": {"type": "boolean", "default": true}, "bitrate_mode": {"type": "string", "enum": ["standard", "high"], "default": "standard"}, "end_user_id": {"type": "string"}}}, "input_asset_schema": {"roles": [{"role": "image", "provider_field": "image_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}, {"role": "end_image", "provider_field": "end_image_url", "media_kind": "image", "required": false, "min": 0, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "seedance_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"480p": "0.3034", "720p": "0.3034", "1080p": "0.682", "4k": "0.682"}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'bytedance/seedance-2.0/reference-to-video',
    'video_generation',
    'Seedance 2.0 Reference to Video',
    2000,
    100000,
    9820800,
    true,
    $${"public_id": "bytedance/seedance-2.0/reference-to-video", "provider_endpoint": "bytedance/seedance-2.0/reference-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image", "video", "audio"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"resolution": "720p", "duration": "5", "aspect_ratio": "auto", "generate_audio": true, "bitrate_mode": "standard"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "resolution": {"type": "string", "enum": ["480p", "720p", "1080p", "4k"], "default": "720p"}, "duration": {"type": "string", "enum": ["4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "aspect_ratio": {"type": "string", "enum": ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], "default": "auto"}, "generate_audio": {"type": "boolean", "default": true}, "bitrate_mode": {"type": "string", "enum": ["standard", "high"], "default": "standard"}, "end_user_id": {"type": "string"}}}, "input_asset_schema": {"roles": [{"role": "reference_images", "provider_field": "image_urls", "media_kind": "image", "required": false, "min": 0, "max": 9, "content_type_prefixes": ["image/"]}, {"role": "reference_videos", "provider_field": "video_urls", "media_kind": "video", "required": false, "min": 0, "max": 3, "content_type_prefixes": ["video/"]}, {"role": "reference_audio", "provider_field": "audio_urls", "media_kind": "audio", "required": false, "min": 0, "max": 3, "content_type_prefixes": ["audio/"]}], "constraints": [{"type": "at_least_one_role", "roles": ["reference_images", "reference_videos", "reference_audio"]}, {"type": "requires_any_role_when_role_present", "role": "reference_audio", "roles": ["reference_images", "reference_videos"]}]}, "pricing_formula": {"type": "seedance_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"480p": "0.3034", "720p": "0.3034", "1080p": "0.682", "4k": "0.682"}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'bytedance/seedance-2.0/fast/text-to-video',
    'video_generation',
    'Seedance 2.0 Fast Text to Video',
    2000,
    100000,
    3483360,
    true,
    $${"public_id": "bytedance/seedance-2.0/fast/text-to-video", "provider_endpoint": "bytedance/seedance-2.0/fast/text-to-video", "kind": "video", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"resolution": "720p", "duration": "5", "aspect_ratio": "auto", "generate_audio": true, "bitrate_mode": "standard"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "resolution": {"type": "string", "enum": ["480p", "720p"], "default": "720p"}, "duration": {"type": "string", "enum": ["4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "aspect_ratio": {"type": "string", "enum": ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], "default": "auto"}, "generate_audio": {"type": "boolean", "default": true}, "bitrate_mode": {"type": "string", "enum": ["standard", "high"], "default": "standard"}, "end_user_id": {"type": "string"}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "seedance_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"480p": "0.2419", "720p": "0.2419"}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'bytedance/seedance-2.0/fast/image-to-video',
    'video_generation',
    'Seedance 2.0 Fast Image to Video',
    2000,
    100000,
    3483360,
    true,
    $${"public_id": "bytedance/seedance-2.0/fast/image-to-video", "provider_endpoint": "bytedance/seedance-2.0/fast/image-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"resolution": "720p", "duration": "5", "aspect_ratio": "auto", "generate_audio": true, "bitrate_mode": "standard"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "resolution": {"type": "string", "enum": ["480p", "720p"], "default": "720p"}, "duration": {"type": "string", "enum": ["4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "aspect_ratio": {"type": "string", "enum": ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], "default": "auto"}, "generate_audio": {"type": "boolean", "default": true}, "bitrate_mode": {"type": "string", "enum": ["standard", "high"], "default": "standard"}, "end_user_id": {"type": "string"}}}, "input_asset_schema": {"roles": [{"role": "image", "provider_field": "image_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}, {"role": "end_image", "provider_field": "end_image_url", "media_kind": "image", "required": false, "min": 0, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "seedance_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"480p": "0.2419", "720p": "0.2419"}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'bytedance/seedance-2.0/fast/reference-to-video',
    'video_generation',
    'Seedance 2.0 Fast Reference to Video',
    2000,
    100000,
    2090160,
    true,
    $${"public_id": "bytedance/seedance-2.0/fast/reference-to-video", "provider_endpoint": "bytedance/seedance-2.0/fast/reference-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image", "video", "audio"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"resolution": "720p", "duration": "5", "aspect_ratio": "auto", "generate_audio": true, "bitrate_mode": "standard"}, "parameter_schema": {"type": "object", "required": ["prompt"], "additionalProperties": false, "properties": {"prompt": {"type": "string", "minLength": 1}, "resolution": {"type": "string", "enum": ["480p", "720p"], "default": "720p"}, "duration": {"type": "string", "enum": ["4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "aspect_ratio": {"type": "string", "enum": ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"], "default": "auto"}, "generate_audio": {"type": "boolean", "default": true}, "bitrate_mode": {"type": "string", "enum": ["standard", "high"], "default": "standard"}, "end_user_id": {"type": "string"}}}, "input_asset_schema": {"roles": [{"role": "reference_images", "provider_field": "image_urls", "media_kind": "image", "required": false, "min": 0, "max": 9, "content_type_prefixes": ["image/"]}, {"role": "reference_videos", "provider_field": "video_urls", "media_kind": "video", "required": false, "min": 0, "max": 3, "content_type_prefixes": ["video/"]}, {"role": "reference_audio", "provider_field": "audio_urls", "media_kind": "audio", "required": false, "min": 0, "max": 3, "content_type_prefixes": ["audio/"]}], "constraints": [{"type": "at_least_one_role", "roles": ["reference_images", "reference_videos", "reference_audio"]}, {"type": "requires_any_role_when_role_present", "role": "reference_audio", "roles": ["reference_images", "reference_videos"]}]}, "pricing_formula": {"type": "seedance_seconds", "duration_parameter": "duration", "resolution_parameter": "resolution", "audio_parameter": "generate_audio", "rates": {"480p": "0.14515", "720p": "0.14515"}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/kling-video/v3/pro/text-to-video',
    'video_generation',
    'Kling v3 Pro Text to Video',
    2000,
    100000,
    3528000,
    true,
    $${"public_id": "fal-ai/kling-video/v3/pro/text-to-video", "provider_endpoint": "fal-ai/kling-video/v3/pro/text-to-video", "kind": "video", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"duration": "5", "generate_audio": true, "shot_type": "customize", "aspect_ratio": "16:9", "negative_prompt": "low quality, blurry, distorted", "cfg_scale": 0.5}, "parameter_schema": {"type": "object", "additionalProperties": false, "constraints": [{"type": "exactly_one", "fields": ["prompt", "multi_prompt"]}], "properties": {"prompt": {"type": "string"}, "multi_prompt": {"type": "array", "minItems": 1, "items": {"type": "object"}}, "duration": {"type": "string", "enum": ["3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "generate_audio": {"type": "boolean", "default": true}, "shot_type": {"type": "string", "enum": ["customize", "intelligent"], "default": "customize"}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16", "1:1"], "default": "16:9"}, "negative_prompt": {"type": "string", "default": "low quality, blurry, distorted"}, "cfg_scale": {"type": "number", "minimum": 0, "maximum": 1, "default": 0.5}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "kling_seconds", "duration_parameter": "duration", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.112", "audio": "0.168", "voice_control": "0.196"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/kling-video/v3/pro/image-to-video',
    'video_generation',
    'Kling v3 Pro Image to Video',
    2000,
    100000,
    3528000,
    true,
    $${"public_id": "fal-ai/kling-video/v3/pro/image-to-video", "provider_endpoint": "fal-ai/kling-video/v3/pro/image-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"duration": "5", "generate_audio": true, "shot_type": "customize", "negative_prompt": "low quality, blurry, distorted", "cfg_scale": 0.5}, "parameter_schema": {"type": "object", "additionalProperties": false, "constraints": [{"type": "exactly_one", "fields": ["prompt", "multi_prompt"]}], "properties": {"prompt": {"type": "string"}, "multi_prompt": {"type": "array", "minItems": 1, "items": {"type": "object"}}, "duration": {"type": "string", "enum": ["3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "generate_audio": {"type": "boolean", "default": true}, "shot_type": {"type": "string", "enum": ["customize", "intelligent"], "default": "customize"}, "negative_prompt": {"type": "string", "default": "low quality, blurry, distorted"}, "cfg_scale": {"type": "number", "minimum": 0, "maximum": 1, "default": 0.5}}}, "input_asset_schema": {"roles": [{"role": "start_image", "provider_field": "start_image_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}, {"role": "end_image", "provider_field": "end_image_url", "media_kind": "image", "required": false, "min": 0, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "kling_seconds", "duration_parameter": "duration", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.112", "audio": "0.168", "voice_control": "0.196"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/kling-video/v3/standard/text-to-video',
    'video_generation',
    'Kling v3 Standard Text to Video',
    2000,
    100000,
    2772000,
    true,
    $${"public_id": "fal-ai/kling-video/v3/standard/text-to-video", "provider_endpoint": "fal-ai/kling-video/v3/standard/text-to-video", "kind": "video", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"duration": "5", "generate_audio": true, "shot_type": "customize", "aspect_ratio": "16:9", "negative_prompt": "low quality, blurry, distorted", "cfg_scale": 0.5}, "parameter_schema": {"type": "object", "additionalProperties": false, "constraints": [{"type": "exactly_one", "fields": ["prompt", "multi_prompt"]}], "properties": {"prompt": {"type": "string"}, "multi_prompt": {"type": "array", "minItems": 1, "items": {"type": "object"}}, "duration": {"type": "string", "enum": ["3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "generate_audio": {"type": "boolean", "default": true}, "shot_type": {"type": "string", "enum": ["customize", "intelligent"], "default": "customize"}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16", "1:1"], "default": "16:9"}, "negative_prompt": {"type": "string", "default": "low quality, blurry, distorted"}, "cfg_scale": {"type": "number", "minimum": 0, "maximum": 1, "default": 0.5}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "kling_seconds", "duration_parameter": "duration", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.084", "audio": "0.126", "voice_control": "0.154"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'fal',
    'fal-ai/kling-video/v3/standard/image-to-video',
    'video_generation',
    'Kling v3 Standard Image to Video',
    2000,
    100000,
    2772000,
    true,
    $${"public_id": "fal-ai/kling-video/v3/standard/image-to-video", "provider_endpoint": "fal-ai/kling-video/v3/standard/image-to-video", "kind": "video", "supports_uploaded_inputs": true, "supported_input_types": ["image"], "output_types": ["video"], "pricing_unit": "second", "default_parameters": {"duration": "5", "generate_audio": true, "shot_type": "customize", "negative_prompt": "low quality, blurry, distorted", "cfg_scale": 0.5}, "parameter_schema": {"type": "object", "additionalProperties": false, "constraints": [{"type": "exactly_one", "fields": ["prompt", "multi_prompt"]}], "properties": {"prompt": {"type": "string"}, "multi_prompt": {"type": "array", "minItems": 1, "items": {"type": "object"}}, "duration": {"type": "string", "enum": ["3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"], "default": "5"}, "generate_audio": {"type": "boolean", "default": true}, "shot_type": {"type": "string", "enum": ["customize", "intelligent"], "default": "customize"}, "negative_prompt": {"type": "string", "default": "low quality, blurry, distorted"}, "cfg_scale": {"type": "number", "minimum": 0, "maximum": 1, "default": 0.5}}}, "input_asset_schema": {"roles": [{"role": "start_image", "provider_field": "start_image_url", "media_kind": "image", "required": true, "min": 1, "max": 1, "content_type_prefixes": ["image/"]}, {"role": "end_image", "provider_field": "end_image_url", "media_kind": "image", "required": false, "min": 0, "max": 1, "content_type_prefixes": ["image/"]}]}, "pricing_formula": {"type": "kling_seconds", "duration_parameter": "duration", "audio_parameter": "generate_audio", "rates": {"default": {"no_audio": "0.084", "audio": "0.126", "voice_control": "0.154"}}}, "fal_output_paths": [{"path": "video", "type": "video"}], "fal_allow_generic_url_fallback": false}$$::jsonb
  ),
  (
    'elevenlabs',
    'music_v2',
    'music_generation',
    'Eleven Music v2',
    2000,
    200000,
    200000,
    true,
    $${"public_id": "music_v2", "provider_endpoint": "music", "kind": "audio", "supports_uploaded_inputs": false, "supported_input_types": [], "output_types": ["audio"], "pricing_unit": "minute", "default_parameters": {"modelId": "music_v2", "outputFormat": "mp3_44100_128"}, "parameter_schema": {"type": "object", "additionalProperties": false, "constraints": [{"type": "at_least_one", "fields": ["prompt", "compositionPlan"]}], "properties": {"prompt": {"type": "string"}, "compositionPlan": {"type": "object"}, "musicLengthMs": {"type": "integer", "minimum": 3000, "maximum": 600000}, "outputFormat": {"type": "string", "enum": ["mp3_44100_128", "mp3_48000_192", "pcm_44100", "pcm_48000"], "default": "mp3_44100_128"}, "seed": {"type": "integer"}, "forceInstrumental": {"type": "boolean"}, "respectSectionsDurations": {"type": "boolean"}, "storeForInpainting": {"type": "boolean"}, "signWithC2Pa": {"type": "boolean"}}}, "input_asset_schema": {"roles": []}, "pricing_formula": {"type": "music_minutes", "duration_parameter": "musicLengthMs"}}$$::jsonb
  )
on conflict (provider, model, operation) do update
set display_name = excluded.display_name,
    markup_bps = excluded.markup_bps,
    minimum_charge_usd_micros = excluded.minimum_charge_usd_micros,
    reserve_amount_usd_micros = excluded.reserve_amount_usd_micros,
    enabled = excluded.enabled,
    metadata = excluded.metadata,
    updated_at = now();
